openwide_service_subscription:
    path:     /service/subscription/{userId}/{serviceLinkId}/{status}
    defaults: { _controller: OpenWideServiceBundle:Subscription:addSubscription, _format: json }
    requirements: 
        _format: (xml|json)
        _method: GET
        userId: \d*
        serviceLinkId: \d*
        status: \d*
 