parameters:
    open_wide_publish_service.controller.service_folder.view.class: OpenWide\Publish\ServiceBundle\Controller\ServiceFolderViewController
    open_wide_publish_service.controller.service_link.view.class:   OpenWide\Publish\ServiceBundle\Controller\ServiceLinkViewController
  

services:
    service.controller.service_folder.view:
        class: %open_wide_publish_service.controller.service_folder.view.class%
        arguments:
            - @ezpublish.view_manager
            - @security.context
        parent: ezpublish.controller.content.view

    service.controller.service_link.view:
        class: %open_wide_publish_service.controller.service_link.view.class%
        arguments:
            - @ezpublish.view_manager
            - @security.context
        parent: ezpublish.controller.content.view